"""A ring buffer of anchor worlds, re-measured under current parameters.

Finding a state where the action choice matters is expensive: the rollout has to
reach it and the pilot pass has to prove it separable.  Discarding that state
after one measurement throws away the search, not the measurement.

What is stored is the *world* -- environment state, observations, the partner's
state, the ego's recurrent carry -- never the returns.  Every continuation is
re-run from the stored world with the parameters in force at the time, so the
CRN estimand is exactly the one the training ordering protects: no decision
target is ever fitted to returns generated by a different continuation policy.

The one approximation is the stored ego carry, which was produced by an older
base policy.  The buffer is deliberately small so that staleness is bounded by a
few anchor intervals, and every replayed world carries the update index that
produced it, so its age is a reported number rather than an assumption.
"""

from __future__ import annotations

from typing import Any, NamedTuple

from .types import AnchorSnapshots


class AnchorBuffer(NamedTuple):
    """``capacity`` slots of stored worlds with the update index that filled them.

    ``filled`` counts how many slots hold real worlds, so a buffer that has not
    yet seen ``capacity`` triggers samples only from what it actually has rather
    than from zero-initialised placeholder states.
    """

    snapshots: AnchorSnapshots
    policy_version: Any
    write_index: Any
    filled: Any

    @property
    def capacity(self) -> int:
        return int(self.policy_version.shape[0])

    @property
    def states_per_slot(self) -> int:
        return int(self.snapshots.time_indexes.shape[1])


def init_anchor_buffer(template: AnchorSnapshots, capacity: int) -> AnchorBuffer:
    """Allocate ``capacity`` slots shaped like one trigger's snapshots."""

    import jax
    import jax.numpy as jnp

    if int(capacity) < 1:
        raise ValueError("The anchor buffer needs at least one slot.")
    slots = int(capacity)
    return AnchorBuffer(
        snapshots=jax.tree_util.tree_map(
            lambda value: jnp.zeros((slots,) + value.shape, dtype=value.dtype),
            template,
        ),
        policy_version=jnp.zeros((slots,), dtype=jnp.int32),
        write_index=jnp.asarray(0, dtype=jnp.int32),
        filled=jnp.asarray(0, dtype=jnp.int32),
    )


def push_anchor_buffer(
    buffer: AnchorBuffer, snapshots: AnchorSnapshots, update_index: Any
) -> AnchorBuffer:
    """Overwrite the oldest slot with this trigger's worlds."""

    import jax
    import jax.numpy as jnp

    slot = buffer.write_index
    capacity = buffer.capacity
    return AnchorBuffer(
        snapshots=jax.tree_util.tree_map(
            lambda stored, fresh: stored.at[slot].set(fresh),
            buffer.snapshots,
            snapshots,
        ),
        policy_version=buffer.policy_version.at[slot].set(
            jnp.asarray(update_index, dtype=jnp.int32)
        ),
        write_index=(slot + 1) % capacity,
        filled=jnp.minimum(buffer.filled + 1, capacity),
    )


def sample_anchor_worlds(
    buffer: AnchorBuffer, key: Any, count: int
) -> tuple[AnchorSnapshots, Any]:
    """Draw ``count`` stored worlds uniformly from the filled slots.

    Sampling is over ``(slot, state)`` pairs jointly, so a trigger that happened
    to find many separable states does not get the same weight per *state* as
    one that found few -- every stored world is one draw, which is what makes
    the buffer a pool rather than a schedule.
    """

    import jax
    import jax.numpy as jnp

    capacity = buffer.capacity
    per_slot = buffer.states_per_slot
    live = jnp.maximum(buffer.filled, 1)
    slot_key, state_key = jax.random.split(key)
    slots = jax.random.randint(slot_key, (int(count),), 0, live)
    states = jax.random.randint(state_key, (int(count),), 0, per_slot)
    drawn = jax.tree_util.tree_map(
        lambda value: value[slots, states], buffer.snapshots
    )
    del capacity
    return drawn, buffer.policy_version[slots]


def merge_snapshots(
    fresh: AnchorSnapshots, replayed: AnchorSnapshots, fresh_count: int
) -> AnchorSnapshots:
    """Take the first ``fresh_count`` fresh worlds, then the replayed ones."""

    import jax
    import jax.numpy as jnp

    return jax.tree_util.tree_map(
        lambda new, old: jnp.concatenate((new[: int(fresh_count)], old), axis=0),
        fresh,
        replayed,
    )


__all__ = [
    "AnchorBuffer",
    "init_anchor_buffer",
    "merge_snapshots",
    "push_anchor_buffer",
    "sample_anchor_worlds",
]
