from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np

from .canonical import canonical_hash
from .models import EdgeRecord, PublicState
from .state_codec import PublicStateCodec, concrete_state_to_jsonable

A_RIGHT, A_DOWN, A_LEFT, A_UP, A_STAY, A_INTERACT = 0, 1, 2, 3, 4, 5
DIR_DELTA = {
    A_RIGHT: (1, 0),
    A_DOWN: (0, 1),
    A_LEFT: (-1, 0),
    A_UP: (0, -1),
}

# Runtime branch labels are deliberately aligned with the Gate 2 process branch
# rows. Unknown labels reject the edge instead of entering E_tau.
ACCEPTED_BRANCH_LABELS = {
    "movement_forward_or_turn",
    "movement_blocked_or_stay",
    "collision_or_swap_resolution",
    "structural_no_effect",
    "plate_pile_pickup",
    "ingredient_pile_pickup",
    "counter_pickup",
    "counter_drop",
    "pot_placement_non_full",
    "pot_placement_full_auto_cook",
    "explicit_pot_start_cooking",
    "pot_ready_pickup",
    "button_activation",
    "delivery",
    "recipe_resampling",
    "pot_timestep",
    "button_timestep",
    "time_terminal_update",
}

STATIC_OBJECT_NAMES = {
    0: "empty",
    1: "wall",
    4: "goal",
    5: "pot",
    6: "recipe_indicator",
    7: "button_recipe_indicator",
    9: "plate_pile",
}


@dataclass(frozen=True)
class EdgeCheckOutcome:
    edge: EdgeRecord
    dst_public: PublicState
    dst_hash: str
    next_state: Any


class CertifiedEdgeChecker:
    """Builds source-backed public edges from actual JAXMARL step outcomes.

    This class never admits candidate edges. An edge must be generated by the
    source step wrapper, project to a public successor, classify into accepted
    Gate 2 branch labels, and pass projection consistency.
    """

    def __init__(self, codec: PublicStateCodec, backend: Any) -> None:
        self.codec = codec
        self.backend = backend

    def check_source_step(self, src_public: PublicState, src_hash: str, raw_state: Any, joint_action: tuple[int, ...], seed: int) -> EdgeCheckOutcome:
        outcome = self.backend.step(raw_state, joint_action, seed)
        return self.check_precomputed_outcome(src_public, src_hash, raw_state, joint_action, outcome.next_state)

    def check_precomputed_outcome(self, src_public: PublicState, src_hash: str, raw_state: Any, joint_action: tuple[int, ...], next_state: Any) -> EdgeCheckOutcome:
        """Certify a source step outcome already produced by the backend.

        Batched graph construction obtains source successors through one
        vectorized JAXMARL call and then passes each successor through the same
        branch-classification and projection checks used by single-step mode. No
        candidate edge is admitted here.
        """
        dst_public = self.codec.alpha_tau(next_state)
        dst_hash = self.codec.public_state_hash(dst_public)
        labels = tuple(sorted(self.classify_transition(raw_state, next_state, joint_action)))
        rejected = [label for label in labels if label not in ACCEPTED_BRANCH_LABELS]
        projection_checked = self.codec.public_state_hash(self.codec.alpha_tau(next_state)) == dst_hash
        source_certified = not rejected and projection_checked
        reason = None if source_certified else ";".join(rejected or ["PUBLIC_PROJECTION_MISMATCH"])
        edge_id = canonical_hash({"src": src_hash, "dst": dst_hash, "joint_action": joint_action, "labels": labels}, prefix="edge")
        edge = EdgeRecord(
            edge_id=edge_id,
            src_hash=src_hash,
            dst_hash=dst_hash,
            joint_action=joint_action,
            branch_labels=labels,
            source_certified=source_certified,
            projection_checked=projection_checked,
            rejected_reason=reason,
        )
        return EdgeCheckOutcome(edge=edge, dst_public=dst_public, dst_hash=dst_hash, next_state=next_state)

    def classify_transition(self, before: Any, after: Any, joint_action: tuple[int, ...]) -> set[str]:
        b = concrete_state_to_jsonable(before)
        a = concrete_state_to_jsonable(after)
        labels: set[str] = set()
        if self._positions_or_dirs_changed(b, a):
            labels.add("movement_forward_or_turn")
        if self._collision_or_swap_possible(b, a, joint_action):
            labels.add("collision_or_swap_resolution")
        if all(x in {A_STAY, A_INTERACT} for x in joint_action) and not self._positions_or_dirs_changed(b, a):
            labels.add("movement_blocked_or_stay")
        for agent_i, act in enumerate(joint_action):
            if act == A_INTERACT:
                labels.update(self._classify_interact_for_agent(b, a, agent_i))
        if self._pot_timer_changed_without_direct_interact(b, a):
            labels.add("pot_timestep")
        if self._button_timer_changed_without_direct_interact(b, a):
            labels.add("button_timestep")
        if b.get("recipe") != a.get("recipe"):
            labels.add("recipe_resampling")
        if b.get("time") != a.get("time") or b.get("terminal") != a.get("terminal"):
            labels.add("time_terminal_update")
        if not labels:
            labels.add("structural_no_effect")
        return labels

    def _positions_or_dirs_changed(self, b: dict, a: dict) -> bool:
        return b["agents"]["pos"] != a["agents"]["pos"] or b["agents"]["dir"] != a["agents"]["dir"]

    def _collision_or_swap_possible(self, b: dict, a: dict, joint_action: tuple[int, ...]) -> bool:
        # This detects the need to include the collision/swap branch label; it is
        # not used as a shortcut for certification.
        before_pos = list(zip(b["agents"]["pos"]["x"], b["agents"]["pos"]["y"]))
        after_pos = list(zip(a["agents"]["pos"]["x"], a["agents"]["pos"]["y"]))
        if len(after_pos) != len(set(after_pos)):
            return True
        for i, p in enumerate(before_pos):
            for j, q in enumerate(before_pos):
                if i < j and after_pos[i] == q and after_pos[j] == p and p != q:
                    return True
        # If two agents attempted movement and one projected position did not
        # change, the source collision/blocking machinery may have fired.
        return any(act in DIR_DELTA and before_pos[i] == after_pos[i] for i, act in enumerate(joint_action))

    def _classify_interact_for_agent(self, b: dict, a: dict, agent_i: int) -> set[str]:
        labels: set[str] = set()
        x = int(b["agents"]["pos"]["x"][agent_i])
        y = int(b["agents"]["pos"]["y"][agent_i])
        d = int(b["agents"]["dir"][agent_i])
        dx, dy = self._direction_to_delta(d)
        fx, fy = x + dx, y + dy
        grid = b["grid"]
        if fy < 0 or fy >= len(grid) or fx < 0 or fx >= len(grid[0]):
            return {"structural_no_effect"}
        before_cell = grid[fy][fx]
        after_cell = a["grid"][fy][fx]
        static_obj = int(before_cell[0])
        before_ing = int(before_cell[1])
        before_extra = int(before_cell[2])
        after_ing = int(after_cell[1])
        after_extra = int(after_cell[2])
        inv_before = int(b["agents"]["inventory"][agent_i])
        inv_after = int(a["agents"]["inventory"][agent_i])
        if static_obj == 9 and inv_before == 0 and inv_after != 0:
            labels.add("plate_pile_pickup")
        elif static_obj >= 10 and inv_before == 0 and inv_after != 0:
            labels.add("ingredient_pile_pickup")
        elif static_obj == 1:
            if before_ing != 0 and inv_after != inv_before:
                labels.add("counter_pickup")
            elif before_ing == 0 and inv_before != 0 and after_ing != 0:
                labels.add("counter_drop")
        elif static_obj == 5:
            if inv_before != 0 and after_ing != before_ing:
                if after_extra > before_extra and after_extra > 0:
                    labels.add("pot_placement_full_auto_cook")
                else:
                    labels.add("pot_placement_non_full")
            elif inv_before == 0 and before_ing != 0 and after_extra > before_extra:
                labels.add("explicit_pot_start_cooking")
            elif inv_before == 1 and inv_after != inv_before:
                labels.add("pot_ready_pickup")
        elif static_obj == 7 and after_extra > before_extra:
            labels.add("button_activation")
        elif static_obj == 4 and inv_before != 0:
            labels.add("delivery")
        if not labels:
            labels.add("structural_no_effect")
        return labels

    @staticmethod
    def _direction_to_delta(direction: int) -> tuple[int, int]:
        # JAXMARL Direction: UP=0, DOWN=1, RIGHT=2, LEFT=3.
        return {
            0: (0, -1),
            1: (0, 1),
            2: (1, 0),
            3: (-1, 0),
        }.get(direction, (0, 0))

    def _pot_timer_changed_without_direct_interact(self, b: dict, a: dict) -> bool:
        return self._extra_changed_for_static(b, a, static_obj=5)

    def _button_timer_changed_without_direct_interact(self, b: dict, a: dict) -> bool:
        return self._extra_changed_for_static(b, a, static_obj=7)

    @staticmethod
    def _extra_changed_for_static(b: dict, a: dict, static_obj: int) -> bool:
        for y, row in enumerate(b["grid"]):
            for x, cell in enumerate(row):
                if int(cell[0]) == static_obj and int(cell[2]) != int(a["grid"][y][x][2]):
                    return True
        return False
